### ISSUE TITLE
Fragment Serverlist Response Packets

### ISSUE THREAD

**Issue by Dss0** [XLabsProject/master#228]
`getserversResponse` packets aren't fragmented, therefore having a large number of servers causes the response packet to become very large. this is already starting to cause an issue for people on IW4x as the packets are blocked due to their large size.

**Comment by momo5502** [comment]
client side implementation probably needs to be done first

**Comment by momo5502** [comment]
or at least concurrently

**Comment by momo5502** [comment]
If this is nit actively used to block any separate packages from the master, you might be right: 

RefreshContainer.awatingList = false;

**Comment by momo5502** [comment]
However, not sure if this is the desired way, to just endlessly receive packets from the master without knowing when it's done. But i'll think of something

**Comment by Rackover** [comment]
i checked awatingList  and it's only used for checking for timeout in the server frame, rest of the time we can add up servers to the queue and it _should_ work properly (although i did not test it, but that's what the code says to me)

Regarding your second  comment, i disagree! I think it's perfectly fine to receive the server list in an N number of packets that are neither ordered nor awaited, because the whole process of listing servers requires pinging dozens of addresses anyway, most of which could or could not answer, and is a completely asynchronous and lossy process - which is fine. 

Other solutions like acknowledging or counting packets (for instance including packet index/total number of packets in response body) could hang the client or require additional timeouts to be implemented, and for what ? It will not work better to do it that way, it will be more complicated for the same result. I think it's better to keep these fragmented packets anonymous/unordered given the current use case.
